### ISSUE TITLE
Quantile for skew_normal returns invalid value

### ISSUE THREAD

**Issue by yurybura** [boostorg/math#184] opened 2019-02-18 13:20 UTC
Code example:
```cpp
#include <boost/math/distributions/skew_normal.hpp>
#include <cstdlib>

int main()
{
  boost::math::skew_normal skew(573.39724735636185, 77.0, 4.0);
  const double x = boost::math::quantile(skew, 0.00285612015554148);
  const double y = boost::math::quantile(skew, 0.00285612015554149);
  const double z = boost::math::quantile(skew, 0.00285612015554150);
  std::printf("x=%g\n", x);
  std::printf("y=%g\n", y);
  std::printf("z=%g\n", z);
}
```
Result on Windows 10 + MSVC 19.16.27026.1 + Boost 1.67.0:
```
x=539.858
y=-inf
z=539.858
```
Result on Windows 10 + MSVC 19.16.27026.1 + Boost 1.69.0:
```
x=539.858
y=0
z=539.858
```

**Comment by NAThompson** [comment] 2019-02-18 19:26
I just ran your code on develop, using g++-8. I get:

```
x=539.858
y=539.858
z=539.858
```

Could you clone the `develop` and see if it's still there in your environment?

**Comment by jzmaddock** [comment] 2019-02-18 19:51
I can reproduce, it's a numerical instability that triggers a bug in the Newton-Raphson code, I'm just not sure at present if this is a one off or part of a larger issue...

**Comment by yurybura** [comment] 2019-02-19 12:52
Test project: https://github.com/yurybura/test1
Build log: https://ci.appveyor.com/project/yurybura/test1

**Comment by pabristow** [comment] 2019-02-19 15:03
I can also confirm and that it goes wrong before or here
delta becomes inf while delta1 and delta2 is 1.344e-14

     if(fabs(delta * 2) > fabs(delta2))
      {
         // last two steps haven't converged.
         delta = (delta > 0) ? (result - min) / 2 : (result - max) / 2;  <<<<<
         if (fabs(delta) > fabs(result))
            delta = sign(delta) * result; // protect against huge jumps!
         // reset delta2 so we don't take this branch next time round:
         delta1 = delta;
         delta2 = 3 * delta;
      }

at iteration down to 192 (from a very large max_iterations estimate of 200 - is this right?

but I am not expert enough to see why and how to correct it.

**Comment by jzmaddock** [comment] 2019-02-20 20:53
Fixed in develop in the commit referenced above.

**Comment by yurybura** [comment] 2024-01-25 10:57
Issue is returned in Boost 1.84.0. 
The example returns on MSVC 19.38.33134.0 + Boost 1.84.0:
```
x=539.858
y=-1.43195e+250
z=539.858
```

**Comment by jzmaddock** [comment] 2024-01-25 19:10
Confirmed, though strangely the cause is different this time.

Things to check and improve:

1) The derivative is going to zero - why?
2) The zero-derivative handling code in newton_raphson_iterate needs to be updated along the same lines as the previous fix.
3) The quantile function has no error handling for exhausting the max root iterations.
4) We can probably narrow the search bounds anyway before iterating.

**Comment by jzmaddock** [comment] 2024-01-25 19:23
OK, ignore (1) and (2), this got reverted as part of https://github.com/boostorg/math/pull/1002 which was evidently a bad idea.  (3) and (4) we should still look at.

**Closed** 2024-02-06 12:34 UTC
