### ISSUE TITLE
Tanh-Sinh performance and accuracy issues

### ISSUE THREAD

**Issue by Robert-van-Engelen** [boostorg/math#706] opened 2021-10-12 18:58 UTC
I've been evaluating different implementations of Tanh-Sinh and noticed that Boost's Tanh-Sinh may not perform as expected, often requiring many more function evaluations to achieve the same accuracy as other implementations that use IEEE 754 double.

Tanh-Sinh integration with x=0,1 f(x) should produce the same result as x=0,1 f(1-x), but it appears that Boost's implementation treats the boundary x=0 differently than the boundary x=1. There can always be a small difference, but I'm curious why the difference is substantial for Boost's Tanh-Sinh. Consider for example the results for Tanh-Sinh with x=0,1 f(x)=1/sqrt(sin(pi*x)) where the second is applied to f(1-x):

`auto f = [&](double x) { return 1/sqrt(sin(M_PI*x)); }`
1.66925366746488 error=8.0534e-10 evaluations=586
`auto f = [&](double x) { return 1/sqrt(sin(M_PI*(1.0-x))); }`
1.66925366127015 error=3.39749e-10 evaluations=1172

There is a singularity at x=0 and x=1, which should not be a problem for Tanh-Sinh, but notice that the second integrand takes twice as many evaluations.

More problematic is integrating 1/sqrt(-log(1-x)) over x=0,1 which fails with an exception, even though 1/sqrt(-log(x)) works fine. Both are essentially the same, but reversing the x direction causes a failure with an exception.

Another very problematic example: x^-0.8 integrates fine over x=0,1 but (1-x)^-0.8 takes 267448 evaluations (!) to produce a result with a larger error 10^-3 (!) than the reported 10^-7 by Boost, which is still larger than the given tol=10^-9:

5 error=0 evaluations=74
4.99681841329715 error=2.62587e-07 evaluations=267448

All examples above are performed with tolerance=10^-9.

The benchmark code:
~~~
#include <boost/math/quadrature/tanh_sinh.hpp>

using namespace boost::math::quadrature;

static const double tol = 1E-9;
static int ev = 0;

int main() {

  auto f = [&](double x) { ++ev; return 1/sqrt(sin(M_PI*x)); };
  //auto f = [&](double x) { ++ev; return 1/sqrt(-log(1-x)); };
  //auto f = [&](double x) { ++ev; return pow(x, -0.8); };

  // swap integration "direction", integrating g should be the same as integrating f
  auto g = [&](double x) { ++ev; return f(1.0-x); };

  double error;

  ev = 0;
  double Q1 = tanh_sinh<double>().integrate(f, 0.0, 1.0, tol, &error);
  printf("%.15g error=%g evals=%d\n", Q1, error, ev);

  ev = 0;
  double Q2 = tanh_sinh<double>().integrate(g, 0.0, 1.0, tol, &error);
  printf("%.15g error=%g evals=%d\n", Q2, error, ev);
}
~~~
I've completed a more in-depth comparison and analysis with the assistance of math experts on this [HP Forum thread](https://www.hpmuseum.org/forum/thread-16549.html). We came up with several Tanh-Sinh improvements (tested in C++ and Python) published as a [PDF article](https://www.genivia.com/files/qthsh.pdf). Perhaps this is useful. Feel free to contact me for questions, comments or concerns.

**Comment by Robert-van-Engelen** [comment] 2021-10-14 00:52
@jzmaddock you're welcome! I am excited to share these findings and excited to help out in any way I can.

PS. I made a small addition to the PDF article by adding a table of the final qthsh implementation compared to mpmath and Boost Math. Parts of this table occur in fragments earlier, but it is nicer to have a final table.

**Comment by Robert-van-Engelen** [comment] 2021-10-15 02:26
I don't want the discussion to be about qthsh but rather about improving Boost Math Tanh-Sinh. For starters, it helps to compare the two. I would like to understand the Boost Math Tanh-Sinh implementation decisions and when the decisions are better or when perhaps implementations decisions could be hampering performance.

To compare the two, I ran the 818 integrals against Boost Math Tanh-Sinh with tol=10^-9 and compared the results to qthsh with the same tol=10^-9:

| metric        | Boost Math | qthsh |
| ------------- | ---------- | ----- |
| average evals | 2134.4     | 105   |
| number of nan | 39         | 4     |
| failures      | 120        | 97    |

A failure means that the absolute error of the result exceeds 10^-8, giving the method a 10x window for its estimated convergence error. Some failures should be expected due to periodicity or non-differentiability of an integrand, i.e. Tanh-Sinh is not applicable or can be just lucky to produce a result. There are some of these among the 818 test cases.

Observe that:
- The number of Boost Math Tanh-Sinh NaNs produced is quite high, most can be successfully integrated.
- The number of Boost Math Tanh-Sinh function evaluations is very high compared to other Tanh-Sinh implementations, not only compared to qthsh.

Attached is the sheet with the results: 
[boost-test.xlsx](https://github.com/boostorg/math/files/7350420/boost-test.xlsx)

The code I've used parameterized with $1~$5 for f(), a, b, tol, exact:
~~~
#include <boost/math/quadrature/tanh_sinh.hpp>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#define pi M_PI
#define sign(x) ((x>0)-(x<0))
#define csc(x) (1/sin(x))
#define csch(x) (1/sinh(x))
#define sec(x) (1/cos(x))
#define sech(x) (1/cosh(x))
#define cot(x) (1/tan(x))
#define coth(x) (1/tanh(x))

using namespace boost::math::quadrature;

static int ev = 0;

double f(double x) { ++ev; return $1; }

int main() {
  double s, e = 0;
  try {
    s = tanh_sinh<double>().integrate(f, $2, $3, $4, &e);
  }
  catch (std::exception&) {
    s = 0.0/0.0;
  }
  printf("%.16g,%d,%d,%g,%g\n", s, 0, ev, e, fabs(s-($5)));
}
~~~
The qthsh code is as reported in the article.

With respect to singularities in the middle of the domain, adding a check to the code can catch them effectively. Perhaps use the average of failed points in the middle to determine to quit?

**Comment by Robert-van-Engelen** [comment] 2021-10-19 20:31
> @jzmaddock I've created a branch, with Roberts test data, referenced above for experimenting with improvements.

Most of the test cases are from this [link](https://newtonexcelbach.com/2020/10/29/numerical-integration-with-tanh-sinh-quadrature-v-5-0/) in the article, which should get most of the credit. I just spent time exploring the Mosig method and optimized its implementation with feedback from folks participating in the HP forum discussion.

In addition to the sheets with results, I also wrote some bash scripts to compile the C++ code and run the tests automatically:
`$ ./boost-test.sh < qthsh-test.csv > temprun.csv`
The `temprun.csv` is then simply imported in the sheet. The three files in the zip you'll need:
[boost-test.zip](https://github.com/boostorg/math/files/7376331/boost-test.zip)
 
If I were to improve qthsh, I'd add checks to allow singularities close to the endpoint but not in the middle of the integration range, unless perhaps the user specifies an option to override and permit singularities anywhere. How close to the endpoints? That's a good question.

> In effect we have abrogated responsibility in the way we use the tolerance parameter - it's not a error target, but a termination condition. That's why we recommend using the sqrt of your target as a tolerance - though the issue is that this does not always work. I do note that Michalski & Mosig make the same recommendation though. That not withstanding, I do have some ideas for how to improve things here so they're more obvious / user friendly.

I had decided that a simple termination condition is likely best and intuitive, based on the excellent work on Tanh-Sinh for WP-34S, thinking that the user just wants the integral with N digits precision or close enough. The qthsh convergence test is different though, to bound the absolute error _and_ the relative error given the specified tolerance, depending on the magnitude of the integration result, i.e. if the result is <<1 this hybrid test puts emphasis on bounding the relative error. Other criteria can be used of course, as long as it is documented, I suppose.

> The other main difference I think is Mosig's variation on the tanh-sinh weights and abscissa calculation. It seems like from what you're saying in your paper that Mosig's variation reaches slightly further out into the tails than standard tanh-sinh?

Mosig's variation does not push the points as quickly towards the endpoints, so it appears to capture slightly more points in the middle, rather. I think this helps to improve cases that don't ideally work as well with Tanh-Sinh. Furthermore, the Tanh-Sinh overhead to produce the abscissas and weights is low. That helps to speed up the integration on slower machines, e.g. calculators. Otherwise, producing the points could be more costly than evaluating _f_ on each point, which can be quite noticeable on slower machines.

I should also add that one might be perfectly content if Tanh-Sinh gives up after 500~2000 or so points, when convergence appears to be slow. At that stage it is clear at that the method fails for the given integrand. In this way, we don't force the method onto periodic or other non-holomorphic functions, because there is no guarantee that the result lies within a given error bound (the number of points in the middle may be too sparse); a different integration method should be used instead. Of course, it is debatable what is best, because the user may have different intentions.

**Comment by Robert-van-Engelen** [comment] 2021-10-20 19:22
@NAThomson thanks for the explanation which makes a lot of sense.

There is another thing I'd like to add that can be useful, which came up as a response to a question about integration accuracy on the HP forum: can the integration method be _inherently_ noisy? E.g. due to internal float inaccuracies to compute abscissas and weights? Simple weights pose no problem, e.g. Simpson, Romberg are exact for (low order) polynomials. Weights derived from table-based methods, such as Gauss-Kronrod may collect small errors in the weight calculations. So I was curious to test this for Tanh-Sinh with a simple constant function integration ∫2dx for x=-10..10 with eps=10^-6 tolerance or about _to make sure we get comparable number of evaluation points_ for each method:

- Gauss-Kronrod G10K21 with IEEE 754 doubles = 40.000 000 000 000 007.
- WP-34S Tanh-Sinh C version with IEEE 754 double: 39.999 999 999 987 885 (23 points)
- qthsh Tanh-Sinh with IEEE 754 double: 40.000 000 000 000 057 (29 points)
- Boost Math Tanh-Sinh with IEEE 754 double: 40.000 000 000 001 464 (25 points)

This is by no means a scientific experiment or should be considered conclusive, because I just picked a constant function as the simplest to test (and so I ran into this bug #702). Also pushing smaller eps will have a corrective effect and the error is smaller than the requested accuracy, so no real harm done! However, this observation may help to evaluate the intrinsic numerical stability and accuracy of the abscissa and weight calculations of the method for larger eps, e.g. test with eps=10^-2 to 10^-9. The qthsh abscissas _a_+_x_ and _b_-_x_ with _x_=_dr_ and weights _w_=(_t_+1/_t_)_r_/(1+_u_) with _r_=2 _u_/(1+_u_) are produced as more tightly coupled pairs depending both on _r_, i.e. without involving other functions like the WP-34S code uses _x_=_dr_ with _r_=sqrt(_ecs_^2_-1)/_ecs_ and _w_=1/(_ecs_^2) with _ecs_=cosh(pi/2sqrt(_ch_^2-1)) see article. IMHO each arithmetic operation or function introduces an error. Longer chains of calculations produce larger errors. Catastrophic cancellation should be avoided at all cost, if possible. Note that qthsh _t_ and _u_ are positive, so no catastrophic cancellations can occur in _t_+1 and 1+_u_.

**Comment by Robert-van-Engelen** [comment] 2021-11-16 17:55
@NAThompson Is there anything you want me to take a look at or help out?

**Comment by NAThompson** [comment] 2021-11-16 23:18
Bah, I think the only thing that could help at this point is a translation of some of the original Japanese literature; e.g.

Takahasi, Hidetosi. "Error estimation in the numerical integration of analytic functions." Rep. Comput. Centre Univ. Tokyo 3 (1970): 41-108.

**Comment by jzmaddock** [comment] 2021-11-17 17:57
> Is there anything you want me to take a look at or help out?

What I have on my HD right now (but not quite ready for public review yet), is a version of the Boost code which rigorously prunes the tails of trivially small values: the code makes many fewer function calls, though still not necessarily as few as qthsh.  At this point I would say the two routines are "different" rather than better or worse: qthsh can make fewer calls, but can also miss significant areas in the tails (examples to come).  What I'm doing now, is working through all the cases where the boost code has high error rates and figuring out what the issue is, at the end, I should have an interesting list (with examples) of archetypical cases where tanhsinh performs badly, some fixable, some not.

**Comment by NAThompson** [comment] 2021-11-17 18:46
@jzmaddock : Will these ideas be useful for exp-sinh and sinh-sinh as well?

**Comment by genivia-inc** [comment] 2021-11-17 21:57
In the end, I would expect a straightforward (but balanced) implementation like qthsh to not be able to beat Boost Tanh-Sinh. But right now, I'm not so sure when looking at the averages.

Practically speaking, the focus of qthsh (and the WP-34S code to begin with) was to reduce CPU cost with a straightforward implementation to produce reasonably accurate results i.e. no bells and whistles e.g. deal with singularities more smartly when in the middle or optimize the transformation of the integration domain.

There are plenty of things that can be further explored.

For example, to push _both_ tails towards 0 instead of just the one in Boost Tanh-Sinh, I'd split the integration domain up into two parts and change variables such that each of the two parts has a 0 bound. That is, int_a,b f(x)dx = int_0,1 f(y)dy + int_0,1 f(z)dz with applicable y and z transformations. It would be interesting to see what the accuracy can be in this case, but also what the impact of integration is i.e. splitting up the domain in two can have benefits but may also have issues depending on the integrand. Didn't test this idea, so I don't know (yet).

**Comment by jzmaddock** [comment] 2021-11-18 12:03
>In the end, I would expect a straightforward (but balanced) implementation like qthsh to not be able to beat Boost Tanh-Sinh. But right now, I'm not so sure when looking at the averages.

It's not so simple, as there are design decisions to be made.

Generally, qthsh performs well because it doesn't go too far out into the tails - this works brilliantly at low precision for bell shaped curves where most of the area is in the middle of the park, but can fail quite badly in some cases.

Consider test case 36: `exp(1 - 1 / x) * cos(1 / x - 1) / x^2 for x = 0 to 1`

At double precision and root-epsilon tolerance I see:

```
Boost: 0.499999999999999888977697537484 error=2.49e-14 evals=279 found error=2.22e-16
qthsh: 0.499999999040809 error=4.77e-09 evals=202 found error=1.92e-09
```

This is with the current code on my HD, my apologies, I will push it soon, but I need to finish reviewing all the dodgy results first!

Now up the precision to cpp_bin_float_50 (I'm using a trivially adapted template version of qthsh) and I see:

```
Boost: 0.5 error=7.83e-27 evals=731 found error=3.26e-48
qthsh: 0.5 error=2.18e-26 evals=1058 found error=2.34e-26
```

If I up the tolerance to 1e-40 then we get:

```
Boost: 0.5 error=2.21e-48 evals=1438 found error=1.34e-50
qthsh: 0.5 error=4.04e-41 evals=2335 found error=5.11e-41
```

So now Boost is thrashing around for no good reason, and qthsh is slowly getting there.  The reason is simply that qthsh is slower to get out into the tails than Boost.

We can argue endlessly over design decisions here, but in general qthsh is missing a small section in the tails compared to Boost, often this has no effect and qthsh makes fewer function calls, but when there's noticeable area in the tails it leads to poorer found errors, and/or entirely missed areas.

**Comment by jzmaddock** [comment] 2022-01-16 17:35
This should all be addressed in develop now.  As mentioned above there are different design decissions leading to differing accuracy/performance tradeoffs depening on the function.

**Closed by jzmaddock** 2022-01-16 17:35 UTC
