### ISSUE TITLE
A tiny grammer mistake in Akima spline example.

### ISSUE THREAD

**Issue by Sanhei** [boostorg/math#806] opened 2022-07-20 09:03 UTC
This is not a bug, if you need C++ to do spline rather than python, but want to solve the problem quickly. In the example, you need to declare template, which miss <vector(double)>. And need to be noticed, this will destroy your vector, actually also make sense, since the y points can be exactly got from spline function, so you don't need them anymore. But in case you miss something.

auto spline = makima<vector(double)>(std::move(x), std::move(y));

**Comment by mborland** [comment] 2022-07-20 15:33
Duplicate of #803

**Closed as completed** 2022-07-20 15:34 UTC
