### ISSUE TITLE
erf<double>() always returns NaN on certain Android-x86 devices (e.g. K900)

### ISSUE THREAD

**Issue by TheLivingOne** [boostorg/math#170] opened 2018-12-10 08:31 UTC
boost::math::erf(double) returns NaN for normal argument (e.g. 1.5, 2...) on certain Android-x86 devices (e.g. K900, Intel Atom Z2580). The same binary works normally on Android emulator and other Android-x86 devices.

boost::math::erf(float) does not have the same problem so the easiest workaround is to use only the float version.

Used compiler: gcc 4.9 (NDK r10e), possibly relevant options:
-march=atom -mtune=atom -m32 -msse3 -mfpmath=sse -fstrict-aliasing -ffast-math -O2 -fno-reciprocal-math

Some Atom-based notebooks with Windows or Linux could also be affected by this problem.

**Comment by jzmaddock** [comment] 2018-12-10 09:49
Yikes.

I don't have access to that platform - are you able to debug or provide any info on what's going wrong?

If there's access to console output then defining BOOST_MATH_INSTRUMENT might give some ideas of what's happening (or at least which version of the function is called internally).  You might also try defining BOOST_MATH_NO_LONG_DOUBLE_MATH_FUNCTIONS just in case it's the `long double` functions that are being called internally.

**Comment by TheLivingOne** [comment] 2018-12-10 11:42
I will try to create a test app and debug it if I can get my hands on the K900 again. Interestingly the bug does not appear on Asus Zenfone 5 that has similar Z2580 CPU (but probably the SoC is a bit newer version). I also tried but could not google up any relevant CPU bug information. Since K900's are getting quite rare, maybe this bug doesn't worth much effort and just should be listed somewhere as a "known issue".

**Comment by NAThompson** [comment] 2018-12-10 17:38
Looks like you are using a fairly old compiler with a fairly new architecture with a complicated set of compiler flags. Definitely possible to get a bad instruction generated; could you add the flag `-fsanitize=undefined` to you example and see what it spits out?

**Comment by jzmaddock** [comment] 2018-12-10 18:22
>Looks like you are using a fairly old compiler with a fairly new architecture with a complicated set of compiler flags. Definitely possible to get a bad instruction generated; could you add the flag -fsanitize=undefined to your example and see what it spits out?

The functions are actually pretty simple: just some basic arithmetic and a call to exp().  My suspicion is that exp() is a non-functioning stub in this case.

**Comment by TheLivingOne** [comment] 2018-12-11 09:05
K900 and Geek are actually quite old and outdated devices (2013 and Android 4.x), even GCC 4.9 is newer (2015) but there are still some users. I don't think that -fsanitize could give anything interesting as the same binary works fine on later devices, Android emulators and etc. so the algorithms should be OK. If there was an uninitialized variable the error would appear on all devices.

Update: the bug reproduces on Asus Fonepad (Intel Atom Z2420 / Intel Atom Z2460).

**Comment by jzmaddock** [comment] 2019-09-15 18:20
Since this is not reproducible without help from the OP, I'm closing down.

**Closed by jzmaddock** 2019-09-15 18:20 UTC
