### ISSUE TITLE
binomial distribution silently underflows when divide-by-zero occurs in ibeta_power_terms

### ISSUE THREAD

**Issue by mckib2** [boostorg/math#799] opened 2022-07-12 16:20 UTC
As reported in https://github.com/scipy/scipy/issues/15101, there is a potential divide-by-zero in [ibeta_power_terms L392-L393](https://github.com/boostorg/math/blob/db2a7cbb44a84c4c9cba62232c07f18b22bd965d/include/boost/math/special_functions/beta.hpp#L392-L393) for some values of n, p, and k, e.g., n=1000, p=0.01, k=996.  This may not be the only instance of a possible divide-by-zero for these parameter choices.

Suggested patch would be to avoid the logarithm calculation on line 393 if `p1 == 0`.  We are also curious why this underflow is not reported according to boost::math policy or why we can't reproduce any observable issue when run as a simple C++ application (GCC 9), e.g.:

```cpp
#include <iostream>
#include "boost/math/distributions/binomial.hpp"

int main() {
  constexpr int n = 1000;
  constexpr double p = .01;
  constexpr int k = 996;
  boost::math::binomial_distribution<double> b(n, p);
  std::cout << std::setprecision(16) << "ans is " << boost::math::pdf(b, k) << std::endl;
  return 0;
}

```

**Comment by fangzh-umich** [comment] 2022-07-13 14:24
As for reproducing in a simple C++ application, there are two things. First, `boost::math::pdf` with a `binomial_distribution` by default promotes `double` to `long double`, and `float` to `double`. Second, the divide-by-zero warning is caused by a floating point exception, which we have to check manually in C++.

So to reproduce:
```cpp
#include <iostream>
#include "boost/math/distributions/binomial.hpp"
#include <cfenv>

#pragma STDC FENV_ACCESS ON

int main() {
  constexpr int n = 1000;
  constexpr double p = .01;
  constexpr int k = 996;
  boost::math::binomial_distribution<float> b(n, p);
  std::cout << std::setprecision(16) << "ans is " << boost::math::pdf(b, k) << std::endl;
  if(std::fetestexcept(FE_DIVBYZERO)) {
    std::cout << "division by zero reported\n";
  } else {
    std::cout << "divsion by zero not reported\n";
  }
  return 0;
}
```
This should output `division by zero reported`.

**Comment by mckib2** [comment] 2022-07-14 16:06
@fangzh-umich Thanks for clarifying that.  Do you think it's enough to check if `p1 == 0` or are there other changes you can see that would need to be made?  If it's that easy, we may be able to quickly patch it downstream

**Comment by jzmaddock** [comment] 2022-07-14 16:47
If it makes any difference, this is next on my hit list of bugs to squash.  It will be too late for Boost-1.80 now though :(

**Comment by mckib2** [comment] 2022-07-14 16:56
> If it makes any difference, this is next on my hit list of bugs to squash. It will be too late for Boost-1.80 now though :(

No worries -- we have an easy workaround for now, but want to help out with getting an upstream fix for everyone else as well

**Comment by jzmaddock** [comment] 2022-07-15 18:20
@mckib2 Can you see if the PR referenced above is sufficient?

Note that your test case does not (and can not?) trigger a divide by zero:  the only division is in line 392:

```
            T p1 = pow(b1, a / b);
```

And b is always > 0 as checked at the start of ibeta_derivative when it verifies its parameters.  It would be nonsensical in any case, as b <= 0 would require k > n in the distribution.

Unless I'm missing something?

**Comment by mckib2** [comment] 2022-07-15 18:27
The issue is a divide by zero reported when computing the log as detailed in this comment: https://github.com/scipy/scipy/issues/15101#issuecomment-1181889203

**Comment by mckib2** [comment] 2022-07-15 18:30
> Can you see if the PR referenced above is sufficient?

By looking at it, I don't believe this will resolve it as the divide-by-zero bit will still be flipped, but I'll be able to try this patch in situ later today

**Comment by jzmaddock** [comment] 2022-07-15 18:37
Ah, my bad, just pushed a fix for that to the PR.

Sorry I was looking for a literal divide by zero, not a synthesised one inside std::log.

**Closed** 2022-07-16 08:33 UTC

**Comment by mckib2** [comment] 2022-07-16 16:37
@jzmaddock  FYI -- just tested your patch, works perfectly!  Many thanks

**Comment by jzmaddock** [comment] 2022-07-16 19:18
Thanks for the confirmation.
